apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::945912092545:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1UAITIXV53M8S
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::945912092545:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-13T09:27:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1521"
  uid: af345152-0d47-44c5-b170-e48fcb3bf827
